spring.application.name=auth-service

server.address=0.0.0.0
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:15432/auth_db
spring.datasource.username=postgres
spring.datasource.password=qweasdzxc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


jwt.secret=QWxpY2VJc0FKYXZhRGV2ZWxvcGVyQW5kU2hlTG92ZXNTcHJpbmdCb290QW5kQ29mZmVl